apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: orderflow
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin
  KEYCLOAK_CLIENT_SECRET: 9IG90CXur0kP4ef1vq2iBForoBg5ZkVq
