apiVersion: v1
kind: ConfigMap
metadata:
  name: services-config
  namespace: orderflow
data:
  ORDER_SERVICE_URL: "http://order-service.orderflow.svc.cluster.local:20002"
  SHIPPING_SERVICE_URL: "http://mock-shipping-service.orderflow.svc.cluster.local:10000/shipping/"
  CORS_ALLOWED_ORIGINS: "*"
