spring.application.name=UserMicroservice
server.port=20000

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/orderflow}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/orderflow/protocol/openid-connect/certs}

keycloak.server-url=${KEYCLOAK_SERVER_URL:http://localhost:8080/}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:9IG90CXur0kP4ef1vq2iBForoBg5ZkVq}
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

jwt.auth.converter.resoure-id=orderflow-api
jwt.auth.converter.principle-attribute=preferred_username

