apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: orderflow
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: orderflow-notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 20004
          envFrom:
            - configMapRef:
                name: kafka-config
          env:
            - name: SERVER_PORT
              value: "20004"
          readinessProbe:
            tcpSocket:
              port: 20004
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 20004
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
