apiVersion: v1
kind: Service
metadata:
  name: mock-shipping-service
  namespace: orderflow
spec:
  selector:
    app: mock-shipping-service
  ports:
    - port: 10000
      targetPort: 10000
  type: ClusterIP
