apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: orderflow
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: orderflow-user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 20000
          envFrom:
            - configMapRef:
                name: kafka-config
            - configMapRef:
                name: keycloak-config
            - configMapRef:
                name: services-config
          env:
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_CLIENT_SECRET
          readinessProbe:
            tcpSocket:
              port: 20000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 20000
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
