// user.service.ts
import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';
import { Product } from './product.model';

@Injectable({
  providedIn: 'root'
})
export class ProductService {
  private readonly apiUrl = 'http://localhost:20001/product';

  constructor(private http: HttpClient) {}

  getProducts(): Observable<Product[]> {
    return this.http.get<Product[]>(this.apiUrl, {
      headers: new HttpHeaders({
        'Authorization': `Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJuaERJREFhNmZqbm1Ta3NEZEd1SldhdC1jUUxYYzlYN2FlVmdUODhiUEFnIn0.eyJleHAiOjE3NTYzODQyMjUsImlhdCI6MTc1NjM4MzkyNSwianRpIjoib25ydHJvOjNkZjZkOWQ3LTc4MTgtNzg3Ni00MmJmLTRhZmY5NWU1NDFkNCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9yZWFsbXMvb3JkZXJmbG93IiwiYXVkIjpbInJlYWxtLW1hbmFnZW1lbnQiLCJicm9rZXIiLCJhY2NvdW50Il0sInN1YiI6IjM2NmQwODQyLThkOWMtNGYwMC1hODlkLTY1ZmRmMmUyMmRiMiIsInR5cCI6IkJlYXJlciIsImF6cCI6Im9yZGVyZmxvdy1hcGkiLCJzaWQiOiI2ZmY0N2YwNS1hNzg4LTRkZmYtYmIwYi1hY2U2MmU4MTE4MzEiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtb3JkZXJmbG93Iiwib2ZmbGluZV9hY2Nlc3MiLCJhZG1pbiIsInVtYV9hdXRob3JpemF0aW9uIiwidXNlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsibWFuYWdlLWV2ZW50cyIsIm1hbmFnZS1yZWFsbSIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsIm1hbmFnZS1hdXRob3JpemF0aW9uIiwibWFuYWdlLWNsaWVudHMiLCJxdWVyeS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJvcmRlcmZsb3ctYXBpIjp7InJvbGVzIjpbImFkbWluIl19LCJicm9rZXIiOnsicm9sZXMiOlsicmVhZC10b2tlbiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsInZpZXctYXBwbGljYXRpb25zIiwidmlldy1jb25zZW50Iiwidmlldy1ncm91cHMiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsIm1hbmFnZS1jb25zZW50IiwiZGVsZXRlLWFjY291bnQiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IkthbGVteiBLYWxlbXoiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJrYWxlbXoiLCJnaXZlbl9uYW1lIjoiS2FsZW16IiwiZmFtaWx5X25hbWUiOiJLYWxlbXoiLCJlbWFpbCI6ImthbGVtekBnbWFpbC5jb20ifQ.CMj9RfTprzv9Wy7xdbdRlBLky9gC94Gk1iKVQBxeqeONUFv1G7a-tFCNDnd3r_zt0HPsczC1TtNrTPshXpzzs3Pkd9kt8CWI7orAQ0lfDnl1KVQGeVmngtSzRF0YSsjJU2mm1yUK0gnCtYfmLEb1vaMeHzOd5R4_OlGU-EWxSDPWATH0TeeeM8sUIuaAC3JbmBLwHOspJ9RyVY1T3yEN8bsJPV05rqUsKEQou8cjLlf0LWCSGRIqgd8acgO-fWZnEHbJTMwGSmPLbvD-xRMOUeEMTYleCDWycQRR4VD0kIy7e5LugB8S0ue4QO4r1t-5FbJRY2LMb3zx2eWS4IZIQg`
      })
    });
  }
}
